name: Deploy GitHub wiki
description: 🚀 GitHub Action to publish files to a GitHub wiki for deployments

branding:
  icon: upload-cloud
  color: blue

inputs:
  github-server-url:
    description:
      The base URL for the GitHub instance that you are trying to clone from,
      will use environment defaults to fetch from the same instance that the
      workflow is running from unless specified. Example URLs are
      https://github.com or https://my-ghes-server.example.com. The default is
      github.server_url.
    default: ${{ github.server_url }}
  repository:
    description:
      The repository slug to use as the base project target of the wiki. The
      contents will be deployed to this repository's wiki tab, not the
      repository itself. Use this if you are pushing contents across the
      repository boundary. Defaults to the current repository from
      github.repository.
    default: ${{ github.repository }}
  token:
    description:
      Set this if you are pushing to a different repository. This token will
      need write permissions. The default is github.token.
    default: ${{ github.token }}
  path:
    description:
      Path of the directory containing the wiki files to be deployed. Defaults
      to the wiki/ folder.
    default: wiki

outputs:
  wiki-url:
    description:
      The URL of the published GitHub wiki hompage. Usually something like
      https://github.com/octocat/project/wiki.
    value: ${{ steps.main.outputs.wiki-url }}

runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: bash "$GITHUB_ACTION_PATH/main.sh"
      env:
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
