name: Upload wiki
description: 📥 Upload your GitHub wiki

branding:
  icon: upload-cloud
  color: blue

inputs:
  server-url:
    default: ${{ github.server_url }}
  repository:
    default: ${{ github.repository }}
  token:
    default: ${{ github.token }}
  path:
    default: .
  delete:
    default: true

outputs:
  wiki-git-url:
    value: ${{ steps.main.outputs.wiki-git-url }}

runs:
  using: composite
  steps:
    - id: main
      shell: bash
      run: '"$GITHUB_ACTION_PATH/main.sh"'
      env:
        INPUT_SERVER_URL: ${{ inputs.server-url }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DELETE: ${{ inputs.delete }}
