name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - wiki/**
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - wiki/**
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-action:
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: main
        uses: ./
        with:
          path: test
      - run: '[[ $OUTPUT_WIKI_URL == https://github.com/actions4gh/deploy-wiki/wiki ]]'
        env:
          OUTPUT_WIKI_URL: ${{ steps.main.outputs.wiki-url }}
