name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - wiki/**
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - wiki/**
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test-action:
    concurrency: wiki-write
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        delete: [true, false]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: main
        uses: ./
        with:
          path: test
          delete: ${{ matrix.delete }}
      - run: echo "$OUTPUT_SHA"
        env:
          OUTPUT_SHA: ${{ steps.main.outputs.sha }}
